# -- Markup --
# These settings are required for the theme to function.

[goldmark]
  [goldmark.renderer]
    unsafe = true

  [goldmark.parser]
    [goldmark.parser.attribute]
      block = true
      title = true
      
[highlight]
  style = 'native'

[tableOfContents]
  startLevel = 1
  endLevel = 2
