[[main]]
  name = "🗣️"
  pageRef = "broadcast"
  weight = 10

[[main]]
  name = "Student Life"
  weight = 20

[[main]]
  name = "Blog"
  parent = "Student Life"
  pageRef = "blog"
  weight = 21

# [[main]]
#   name = "Series"
#   parent = "Student Life"
#   pageRef = "series"
#   weight = 22

[[main]]
  name = "Bloggers"
  parent = "Student Life"
  pageRef = "authors"
  weight = 23

[[main]]
  name = "Portfolios"
  parent = "Student Life"
  pageRef = "portfolios"
  weight = 24

[[main]]
  name = "Community"
  weight = 30

[[main]]
  name = "About Us"
  parent = "Community"
  pageRef = "about"
  weight = 31

[[main]]
  name = "Contact"
  parent = "Community"
  pageRef = "contact"
  weight = 32

[[main]]
  name = "Careers & Alumni"
  parent = "Community"
  pageRef = "alumni"
  weight = 33

[[main]]
  name = "Academia & Research"
  parent = "Community"
  pageRef = "papers"
  weight = 34

[[main]]
  name = "Explore"
  weight = 40

[[main]]
  name = "Projects"
  parent = "Explore"
  pageRef = "projects"
  weight = 41

[[main]]
  name = "Guides"
  parent = "Explore"
  pageRef = "guides"
  weight = 42  

[[main]]
  name = "Docs"
  parent = "Explore"
  pageRef = "docs"
  weight = 43
  
[[main]]
  pre  = "github"
  url = "https://github.com/AMTESFUNAAB/amtes-blog"
  weight = 60

